name: Deploy to VPS via SSH

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy en VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd /home/devgustavo/${{ secrets.VPS_USER }}/portfolio || git clone git@github.com:gafc2001/gafc2001.github.io.git && cd portfolio

            git pull origin main

            docker stop portfolio || true
            docker rm portfolio || true

            docker build -t portfolio:latest .
            docker run -d -p 8080:80 --name portfolio portfolio:latest
          EOF
